#!/bin/bash

RUNDECK_NAME="http://rundeck.labs.in"

create_container() {
    echo "Creating the container on Deveploment Environment"
    docker rm -f rundeck || echo

    mkdir -p /srv/docker/rundeck/plugins  && \
        docker run -P -v /srv/docker/rundeck/plugins:/opt/rundeck-plugins -p 32777:4440 -e SERVER_URL=$RUNDECK_NAME -dit --name rundeck jordan/rundeck
}

deploy() {
    echo "Start build/deploy of package"
    
    LIBS_FILE="$(ls lib/*.jar | tr '\n' ' ')" mvn install -B -V $* && (
        docker container exec rundeck rm -rf /var/lib/rundeck/libext/cache
        for file in target/*.jar; do
            echo "cleaning ${file} from rundeck plugin directory"
            sudo rm -rf /srv/docker/rundeck/plugins/$file
            echo "Copying ${file} to rundeck plugin directory"
            sudo cp $file /srv/docker/rundeck/plugins
        done
        docker container restart rundeck 
    )
}

clean() {
    echo "House cleaning"
    test -d target/ && rm -rf target
    for file in /src/docker/rundeck/plugins/*.jar; do
        sudo rm -rf $file 
    done
    docker rm -f rundeck || echo 
}

case $1 in
    create_container) create_container ;;
    deploy) deploy ;;
    clean) clean ;;
    bash) docker container exec -it rundeck /bin/bash ;;
    *)
        echo "Usage: $0 create_container|deploy|clean"
        echo "Usage: $0 deploy [MAVEN_OPTIONS]"
        ;;
esac

